server:
  port: 8060
  address: localhost
#数据库的连接信息
spring:
  database:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.6:3306/tb_account
    username: remote_user
    password: jintian123
#日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zhoutong.learn.model