server:
  port: 8060
  address: 0.0.0.0
#数据库的连接信息
spring:
  config:
    import: classpath:sql.yml
#日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.zhoutong.learn.model
jwt:
  expiration: 3600000
  signedkey: comzhoutonglearnmodelpropertiessignedkeyfortestokjbsheitamde
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    com-zhoutong: DEBUG
util:
  name: zhoutong
  age: 18
  address: hubeiprovince